### ISSUE TITLE
Actual 2D floor plan images instead of density maps Density Map

### ISSUE THREAD

**Issue by ogencoglu** [woodfrog/poly-diffuse#3]
Thanks for the great work!

In your paper it is mentioned that point clouds are converted to top-view point-density images as inputs.

I was wondering if your work and implementation can be utilized to detect the rooms and walls directly from a real 2D floor plan image? Would you be able to provide a pipeline for a single image input without having to request access and download whole datasets? Or maybe an example sample for the density-map.

**Comment by woodfrog** [comment]
You can adapt the current sampling codes to get an inference pipeline for a single image input -- simply cleaning the data loading codes while keeping the necessary pre-processing steps for the input density image. However, to make the model work well for 2D floorplan images instead of density images, you will need to prepare such a dataset and re-train the model.

For an example sample of the density map, there are many in the paper, like the one below:
<img width="157" alt="Screenshot 2023-07-14 at 15 37 38" src="https://github.com/woodfrog/poly-diffuse/assets/13405255/d2a33b32-8d53-4b10-af3d-a65da97b8636">
Or if you download the processed dataset with the link in README, these images are already included.

**Comment by ogencoglu** [comment]
Thanks a lot. Appreciated!
